# Generated by Django 5.2.4 on 2025-07-26 19:04

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='posts/default.png', upload_to=blog.models.user_directory_path),
        ),
    ]
