# Generated by Django 5.2.4 on 2025-07-28 20:36

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_comment_image_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='posts/default.png', null=True, upload_to=blog.models.user_directory_path),
        ),
    ]
