# Generated by Django 5.2.4 on 2025-07-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comment_options_alter_post_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publish',
            new_name='published_at',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique_for_date='published_at'),
        ),
    ]
