# Generated by Django 5.2.5 on 2025-08-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbs',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbsdown',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbsup',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
