# Generated by Django 5.2.5 on 2025-09-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alternative text for the image', max_length=255, null=True),
        ),
    ]
